defaults:
  - encoder: resnet
  - data: cifar10
  - optim: adam
  - loss: triplet_supervised

n_batches_accumalation: 8

secrets:
  wandb_key: ''

hydra:
  run:
    dir: ./outputs/${data.name}/${loss.name}/${hydra.job.name}/
  sweep:
    dir: multirun/${data.name}
    subdir: ${hydra.job.override_dirname}