defaults:
  - encoder: resnet
  - data: cifar10
  - optim: adam
  - loss: triplet_supervised

n_batches_accumalation: 16

secrets:
  wandb_key: '*'

hydra:
  run:
    dir: ./outputs/${data.name}/${loss.name}/${now:%Y-%m-%d_%H-%M-%S}/
  sweep:
    dir: multirun/${loss.name}/${optim.name}/
    subdir: ${hydra.job.override_dirname}/data=${data.name}
  job:
    config:
      override_dirname:
        exclude_keys:
          - data
