original_data: 'cifar10'
original_method: 'random'
new_data: 'caltech'
method: 'linear'
original_optim: 'adam'

n_classes: 101
embedding_dim: 128
batch_size: 32
need_logits: False

secrets:
  wandb_key: '*'