defaults:
  - encoder: mnist
  - data: mnist
  - optim: adam
  - loss: ntxent

n_batches_accumalation: 8

secrets:
  wandb_key: '*'da  

hydra:
  sweep:
    dir: multirun
    subdir: ${hydra.job.override_dirname}